/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pro1p2_víctorromero;

import java.awt.Color;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author IFRST
 */
public class Intro extends javax.swing.JFrame {

    private Intro Intro;
    protected Juego gameplay;

    /**
     * Creates new form Intro
     */
    public Intro() {
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);

        userAdministrador = new AdministradorUsuario("./src/usuarios.txt");
        userAdministrador.leer();

        LlenarUsuarios();
        this.setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EA_Presents = new javax.swing.JFrame();
        Presents = new javax.swing.JLabel();
        PresentsBlack = new javax.swing.JLabel();
        EA_VR = new javax.swing.JLabel();
        EA_VRBlack = new javax.swing.JLabel();
        PressBlack = new javax.swing.JLabel();
        Press = new javax.swing.JLabel();
        PvZ_Logo = new javax.swing.JLabel();
        Lanzaguisantes = new javax.swing.JLabel();
        Girasol = new javax.swing.JLabel();
        GamePlay = new javax.swing.JLabel();
        Main_Screen = new javax.swing.JFrame();
        lb_name = new javax.swing.JLabel();
        Adventure = new javax.swing.JLabel();
        Tutorial = new javax.swing.JLabel();
        Survival = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        RickRoll = new javax.swing.JLabel();
        MainScreen = new javax.swing.JLabel();
        Tutorial1 = new javax.swing.JLabel();
        Adventure_Game = new javax.swing.JFrame();
        Pause1 = new javax.swing.JButton();
        Sol1 = new javax.swing.JLabel();
        PanelSup_Plants1 = new javax.swing.JPanel();
        Panel_Lanzaguisantes3 = new javax.swing.JLabel();
        Panel_Lanzaguisantes2 = new javax.swing.JLabel();
        Panel_Lanzaguisantes4 = new javax.swing.JLabel();
        LG10 = new Casilla(this);
        LG11 = new Casilla(this);
        LG12 = new Casilla(this);
        LG13 = new Casilla(this);
        LG14 = new Casilla(this);
        LG15 = new Casilla(this);
        LG18 = new Casilla(this);
        LG19 = new Casilla(this);
        LG20 = new Casilla(this);
        LG17 = new Casilla(this);
        LG21 = new Casilla(this);
        LG22 = new Casilla(this);
        LG23 = new Casilla(this);
        LG24 = new Casilla(this);
        LG25 = new Casilla(this);
        LG26 = new Casilla(this);
        LG27 = new Casilla(this);
        LG28 = new Casilla(this);
        LG29 = new Casilla(this);
        LG30 = new Casilla(this);
        LG31 = new Casilla(this);
        LG32 = new Casilla(this);
        LG33 = new Casilla(this);
        LG34 = new Casilla(this);
        LG35 = new Casilla(this);
        LG36 = new Casilla(this);
        LG37 = new Casilla(this);
        LG38 = new Casilla(this);
        LG39 = new Casilla(this);
        LG41 = new Casilla(this);
        LG42 = new Casilla(this);
        LG43 = new Casilla(this);
        LG44 = new Casilla(this);
        LG45 = new Casilla(this);
        LG46 = new Casilla(this);
        LG47 = new Casilla(this);
        LG48 = new Casilla(this);
        LG49 = new Casilla(this);
        LG50 = new Casilla(this);
        LG51 = new Casilla(this);
        LG52 = new Casilla(this);
        LG53 = new Casilla(this);
        LG54 = new Casilla(this);
        LG55 = new Casilla(this);
        LG56 = new Casilla(this);
        LG57 = new javax.swing.JLabel();
        LG58 = new Casilla(this);
        LG59 = new Casilla(this);
        jLabel6 = new javax.swing.JLabel();
        SunBoard1 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        PanelInf_Plants1 = new javax.swing.JPanel();
        Adventure_Background1 = new javax.swing.JLabel();
        Tutorial_Game = new javax.swing.JFrame();
        Pause = new javax.swing.JButton();
        Sol = new javax.swing.JLabel();
        LG1 = new Casilla(this);
        LG2 = new Casilla(this);
        LG3 = new Casilla(this);
        LG4 = new Casilla(this);
        LG5 = new Casilla(this);
        LG6 = new Casilla(this);
        LG7 = new Casilla(this);
        LG8 = new Casilla(this);
        LG9 = new Casilla(this);
        jLabel1 = new javax.swing.JLabel();
        Panel_Lanzaguisantes = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SunBoard = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        PanelSup_Plants = new javax.swing.JPanel();
        PanelInf_Plants = new javax.swing.JPanel();
        Tutorial_Background = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Survival_Game = new javax.swing.JFrame();
        LG16 = new Casilla(this);
        LG40 = new Casilla(this);
        LG60 = new Casilla(this);
        LG61 = new Casilla(this);
        LG62 = new Casilla(this);
        LG63 = new Casilla(this);
        LG64 = new Casilla(this);
        LG65 = new Casilla(this);
        LG66 = new Casilla(this);
        LG67 = new Casilla(this);
        LG68 = new Casilla(this);
        LG69 = new Casilla(this);
        LG70 = new Casilla(this);
        LG71 = new Casilla(this);
        LG72 = new Casilla(this);
        LG73 = new Casilla(this);
        LG74 = new Casilla(this);
        LG75 = new javax.swing.JLabel();
        LG76 = new Casilla(this);
        LG87 = new Casilla(this);
        LG88 = new Casilla(this);
        LG89 = new Casilla(this);
        LG90 = new Casilla(this);
        LG91 = new Casilla(this);
        LG92 = new Casilla(this);
        LG93 = new Casilla(this);
        LG95 = new Casilla(this);
        LG105 = new Casilla(this);
        jLabel12 = new javax.swing.JLabel();
        SunBoard2 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        PanelSup_Plants2 = new javax.swing.JPanel();
        Panel_Lanzaguisantes5 = new javax.swing.JLabel();
        Panel_Lanzaguisantes6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        PanelInf_Plants2 = new javax.swing.JPanel();
        Pause2 = new javax.swing.JButton();
        Adventure_Background2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Pause_Screen_TUTORIAL = new javax.swing.JFrame();
        ResumeGame = new javax.swing.JButton();
        SaveandLeave = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Pause_Screen_ADVENTURE = new javax.swing.JFrame();
        ResumeGame1 = new javax.swing.JButton();
        SaveandLeave1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        Pause_Screen_SURVIVAL = new javax.swing.JFrame();
        ResumeGame2 = new javax.swing.JButton();
        SaveandLeave2 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        cb_users = new javax.swing.JComboBox<>();
        NewPlayer = new javax.swing.JButton();
        VR_Presents = new javax.swing.JLabel();
        VR_PresentsBlack = new javax.swing.JLabel();
        VR = new javax.swing.JLabel();
        TapToStart = new javax.swing.JLabel();
        Pantalla = new javax.swing.JLabel();

        EA_Presents.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Presents.setFont(new java.awt.Font("Have Heart Two", 0, 70)); // NOI18N
        Presents.setForeground(new java.awt.Color(255, 255, 255));
        Presents.setText("Presents");
        EA_Presents.getContentPane().add(Presents, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 190, 60));

        PresentsBlack.setFont(new java.awt.Font("Have Heart Two", 0, 70)); // NOI18N
        PresentsBlack.setText("Presents");
        EA_Presents.getContentPane().add(PresentsBlack, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 190, 80));

        EA_VR.setBackground(new java.awt.Color(255, 0, 0));
        EA_VR.setFont(new java.awt.Font("Ghostphobia", 1, 80)); // NOI18N
        EA_VR.setForeground(new java.awt.Color(255, 153, 0));
        EA_VR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EA_VR.setText("EA & VR ");
        EA_VR.setToolTipText("");
        EA_VR.setMaximumSize(new java.awt.Dimension(780, 550));
        EA_VR.setMinimumSize(new java.awt.Dimension(780, 550));
        EA_Presents.getContentPane().add(EA_VR, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 420, 70));

        EA_VRBlack.setBackground(new java.awt.Color(255, 0, 0));
        EA_VRBlack.setFont(new java.awt.Font("Ghostphobia", 1, 80)); // NOI18N
        EA_VRBlack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EA_VRBlack.setText("EA & VR ");
        EA_VRBlack.setToolTipText("");
        EA_Presents.getContentPane().add(EA_VRBlack, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 400, 70));

        PressBlack.setBackground(new java.awt.Color(0, 255, 0));
        PressBlack.setFont(new java.awt.Font("Ghostphobia", 1, 40)); // NOI18N
        PressBlack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PressBlack.setText("PRESS TO CONTINUE");
        EA_Presents.getContentPane().add(PressBlack, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 370, 50));

        Press.setBackground(new java.awt.Color(0, 255, 0));
        Press.setFont(new java.awt.Font("Ghostphobia", 1, 40)); // NOI18N
        Press.setForeground(new java.awt.Color(255, 255, 0));
        Press.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Press.setText("PRESS TO CONTINUE");
        EA_Presents.getContentPane().add(Press, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, 380, 50));

        PvZ_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1p2_víctorromero/Images/Plants_vs_Zombies_logo.png"))); // NOI18N
        PvZ_Logo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PvZ_Logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PvZ_LogoMouseClicked(evt);
            }
        });
        EA_Presents.getContentPane().add(PvZ_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 410, 240));

        Lanzaguisantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1p2_víctorromero/Images/ANIMACION_LanzaGuisantes.gif"))); // NOI18N
        EA_Presents.getContentPane().add(Lanzaguisantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, 30, 590, 530));

        Girasol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1p2_víctorromero/Images/Girasol.gif"))); // NOI18N
        EA_Presents.getContentPane().add(Girasol, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, -20, 280, 540));

        GamePlay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GamePlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1p2_víctorromero/Images/Gameplay.jpg"))); // NOI18N
        EA_Presents.getContentPane().add(GamePlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 560));

        Main_Screen.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_name.setBackground(new java.awt.Color(55, 47, 0));
        lb_name.setFont(new java.awt.Font("Ghostphobia", 0, 24)); // NOI18N
        lb_name.setForeground(new java.awt.Color(255, 255, 255));
        lb_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_name.setOpaque(true);
        Main_Screen.getContentPane().add(lb_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 240, 30));

        Adventure.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Adventure.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdventureMouseClicked(evt);
            }
        });
        Main_Screen.getContentPane().add(Adventure, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 260, 70));

        Tutorial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tutorial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TutorialMouseClicked(evt);
            }
        });
        Main_Screen.getContentPane().add(Tutorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 260, 70));

        Survival.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Survival.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SurvivalMouseClicked(evt);
            }
        });
        Main_Screen.getContentPane().add(Survival, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 220, 70));

        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        Main_Screen.getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 160, 50));

        RickRoll.setBackground(new java.awt.Color(105, 99, 67));
        RickRoll.setFont(new java.awt.Font("Ghostphobia", 0, 18)); // NOI18N
        RickRoll.setForeground(new java.awt.Color(204, 204, 0));
        RickRoll.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RickRoll.setText("If this is not you... click here");
        RickRoll.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        RickRoll.setOpaque(true);
        RickRoll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RickRollMouseClicked(evt);
            }
        });
        Main_Screen.getContentPane().add(RickRoll, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 250, 30));

        MainScreen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainScreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1p2_víctorromero/Images/MainScreen5.jpg"))); // NOI18N
        Main_Screen.getContentPane().add(MainScreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 590));
        Main_Screen.getContentPane().add(Tutorial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 260, 70));

        Adventure_Game.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pause1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1p2_víctorromero/Images/Pause.png"))); // NOI18N
        Pause1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pause1MouseClicked(evt);
            }
        });
        Pause1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pause1ActionPerformed(evt);
            }
        });
        Adventure_Game.getContentPane().add(Pause1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 190, 50));

        Sol1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Sol1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1p2_víctorromero/Images/Sun2.png"))); // NOI18N
        Sol1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sol1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sol1MouseClicked(evt);
            }
        });
        Adventure_Game.getContentPane().add(Sol1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 110, 100));

        PanelSup_Plants1.setBackground(new java.awt.Color(55, 47, 0));
        PanelSup_Plants1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        Panel_Lanzaguisantes3.setBackground(new java.awt.Color(51, 51, 255));
        Panel_Lanzaguisantes3.setForeground(new java.awt.Color(255, 255, 255));
        Panel_Lanzaguisantes3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Panel_Lanzaguisantes3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1p2_víctorromero/Images/Tarjeta_lanzaguisantes.png"))); // NOI18N
        Panel_Lanzaguisantes3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel_Lanzaguisantes3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_Lanzaguisantes3MouseClicked(evt);
            }
        });
        PanelSup_Plants1.add(Panel_Lanzaguisantes3);

        Panel_Lanzaguisantes2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Panel_Lanzaguisantes2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1p2_víctorromero/Images/girasol_carta.png"))); // NOI18N
        Panel_Lanzaguisantes2.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        Panel_Lanzaguisantes2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_Lanzaguisantes2MouseClicked(evt);
            }
        });
        PanelSup_Plants1.add(Panel_Lanzaguisantes2);

        Panel_Lanzaguisantes4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Panel_Lanzaguisantes4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1p2_víctorromero/Images/cereza_carta.png"))); // NOI18N
        Panel_Lanzaguisantes4.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        Panel_Lanzaguisantes4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_Lanzaguisantes4MouseClicked(evt);
            }
        });
        PanelSup_Plants1.add(Panel_Lanzaguisantes4);

        Adventure_Game.getContentPane().add(PanelSup_Plants1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 100, 500));
        Adventure_Game.getContentPane().add(LG10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 120, 130));

        LG11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Adventure_Game.getContentPane().add(LG11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 120, 130));
        Adventure_Game.getContentPane().add(LG12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 120, 130));
        Adventure_Game.getContentPane().add(LG13, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 120, 130));
        Adventure_Game.getContentPane().add(LG14, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 120, 130));
        Adventure_Game.getContentPane().add(LG15, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, 120, 130));
        Adventure_Game.getContentPane().add(LG18, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 260, 120, 130));
        Adventure_Game.getContentPane().add(LG19, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 260, 120, 130));
        Adventure_Game.getContentPane().add(LG20, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 260, 120, 130));
        Adventure_Game.getContentPane().add(LG17, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 120, 130));
        Adventure_Game.getContentPane().add(LG21, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 120, 130));
        Adventure_Game.getContentPane().add(LG22, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 120, 130));
        Adventure_Game.getContentPane().add(LG23, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 120, 130));
        Adventure_Game.getContentPane().add(LG24, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 120, 130));
        Adventure_Game.getContentPane().add(LG25, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 120, 130));
        Adventure_Game.getContentPane().add(LG26, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 160, 120, 130));
        Adventure_Game.getContentPane().add(LG27, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, 120, 130));
        Adventure_Game.getContentPane().add(LG28, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 160, 120, 130));
        Adventure_Game.getContentPane().add(LG29, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 160, 120, 130));
        Adventure_Game.getContentPane().add(LG30, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 120, 130));
        Adventure_Game.getContentPane().add(LG31, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 120, 130));
        Adventure_Game.getContentPane().add(LG32, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 120, 130));
        Adventure_Game.getContentPane().add(LG33, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 120, 130));
        Adventure_Game.getContentPane().add(LG34, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 120, 130));
        Adventure_Game.getContentPane().add(LG35, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 60, 120, 130));
        Adventure_Game.getContentPane().add(LG36, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 60, 120, 130));
        Adventure_Game.getContentPane().add(LG37, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 60, 120, 130));
        Adventure_Game.getContentPane().add(LG38, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 60, 120, 130));
        Adventure_Game.getContentPane().add(LG39, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 60, 120, 130));
        Adventure_Game.getContentPane().add(LG41, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 360, 120, 130));
        Adventure_Game.getContentPane().add(LG42, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 120, 130));
        Adventure_Game.getContentPane().add(LG43, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 120, 130));
        Adventure_Game.getContentPane().add(LG44, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, 120, 130));
        Adventure_Game.getContentPane().add(LG45, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, 120, 130));
        Adventure_Game.getContentPane().add(LG46, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 120, 130));
        Adventure_Game.getContentPane().add(LG47, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, 120, 130));
        Adventure_Game.getContentPane().add(LG48, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 460, 120, 130));
        Adventure_Game.getContentPane().add(LG49, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 120, 130));
        Adventure_Game.getContentPane().add(LG50, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, 120, 130));
        Adventure_Game.getContentPane().add(LG51, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 120, 130));
        Adventure_Game.getContentPane().add(LG52, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, 120, 130));
        Adventure_Game.getContentPane().add(LG53, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 460, 120, 130));
        Adventure_Game.getContentPane().add(LG54, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, 120, 130));
        Adventure_Game.getContentPane().add(LG55, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 460, 120, 130));
        Adventure_Game.getContentPane().add(LG56, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 460, 120, 130));
        Adventure_Game.getContentPane().add(LG57, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 440, 120, 130));
        Adventure_Game.getContentPane().add(LG58, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 460, 120, 130));
        Adventure_Game.getContentPane().add(LG59, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 360, 120, 130));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1p2_víctorromero/Images/Sun2.png"))); // NOI18N
        Adventure_Game.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 110, 100));

        SunBoard1.setBackground(new java.awt.Color(55, 47, 0));
        SunBoard1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        SunBoard1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(255, 255, 153));
        jTextField2.setFont(new java.awt.Font("Ghostphobia", 1, 45)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("100");
        jTextField2.setBorder(null);
        jTextField2.setFocusable(false);
        SunBoard1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 90, 40));

        jLabel7.setBackground(new java.awt.Color(255, 255, 153));
        jLabel7.setOpaque(true);
        SunBoard1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 10, 110, 40));

        Adventure_Game.getContentPane().add(SunBoard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 170, 60));

        PanelInf_Plants1.setBackground(new java.awt.Color(86, 86, 2));
        PanelInf_Plants1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Adventure_Game.getContentPane().add(PanelInf_Plants1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 120, 520));

        Adventure_Background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1p2_víctorromero/Images/Background2.jpg"))); // NOI18N
        Adventure_Game.getContentPane().add(Adventure_Background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 620));

        Tutorial_Game.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1p2_víctorromero/Images/Pause.png"))); // NOI18N
        Pause.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PauseMouseClicked(evt);
            }
        });
        Pause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PauseActionPerformed(evt);
            }
        });
        Tutorial_Game.getContentPane().add(Pause, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 190, 50));

        Sol.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Sol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1p2_víctorromero/Images/Sun2.png"))); // NOI18N
        Sol.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SolMouseClicked(evt);
            }
        });
        Tutorial_Game.getContentPane().add(Sol, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 110, 100));

        LG1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LG1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LG1MouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                LG1MouseReleased(evt);
            }
        });
        Tutorial_Game.getContentPane().add(LG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 110, 130));

        LG2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tutorial_Game.getContentPane().add(LG2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 120, 130));
        Tutorial_Game.getContentPane().add(LG3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 110, 130));
        Tutorial_Game.getContentPane().add(LG4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 120, 130));
        Tutorial_Game.getContentPane().add(LG5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 120, 130));
        Tutorial_Game.getContentPane().add(LG6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 120, 130));
        Tutorial_Game.getContentPane().add(LG7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 260, 120, 130));
        Tutorial_Game.getContentPane().add(LG8, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 260, 120, 130));
        Tutorial_Game.getContentPane().add(LG9, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 260, 120, 130));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Ghostphobia", 1, 45)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tutorial_Game.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 100, 40));

        Panel_Lanzaguisantes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Panel_Lanzaguisantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1p2_víctorromero/Images/Tarjeta_lanzaguisantes.png"))); // NOI18N
        Panel_Lanzaguisantes.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        Panel_Lanzaguisantes.setEnabled(false);
        Panel_Lanzaguisantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_LanzaguisantesMouseClicked(evt);
            }
        });
        Tutorial_Game.getContentPane().add(Panel_Lanzaguisantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 59, 100, 130));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1p2_víctorromero/Images/Sun2.png"))); // NOI18N
        Tutorial_Game.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 110, 100));

        SunBoard.setBackground(new java.awt.Color(55, 47, 0));
        SunBoard.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        SunBoard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 153));
        jLabel2.setOpaque(true);
        SunBoard.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 10, 110, 40));

        Tutorial_Game.getContentPane().add(SunBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 170, 60));

        PanelSup_Plants.setBackground(new java.awt.Color(55, 47, 0));
        PanelSup_Plants.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        Tutorial_Game.getContentPane().add(PanelSup_Plants, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 100, 500));

        PanelInf_Plants.setBackground(new java.awt.Color(86, 86, 2));
        PanelInf_Plants.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Tutorial_Game.getContentPane().add(PanelInf_Plants, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 120, 520));

        Tutorial_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1p2_víctorromero/Images/Backyard_Tutorial.jpg"))); // NOI18N
        Tutorial_Game.getContentPane().add(Tutorial_Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 990, 600));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tutorial_Game.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 110, 110));

        Survival_Game.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Survival_Game.getContentPane().add(LG16, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 120, 130));

        LG40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Survival_Game.getContentPane().add(LG40, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 120, 130));
        Survival_Game.getContentPane().add(LG60, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 120, 130));
        Survival_Game.getContentPane().add(LG61, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 120, 130));
        Survival_Game.getContentPane().add(LG62, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 120, 130));
        Survival_Game.getContentPane().add(LG63, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, 120, 130));
        Survival_Game.getContentPane().add(LG64, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 260, 120, 130));
        Survival_Game.getContentPane().add(LG65, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 260, 120, 130));
        Survival_Game.getContentPane().add(LG66, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 260, 120, 130));
        Survival_Game.getContentPane().add(LG67, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 120, 130));
        Survival_Game.getContentPane().add(LG68, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 120, 130));
        Survival_Game.getContentPane().add(LG69, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 120, 130));
        Survival_Game.getContentPane().add(LG70, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 120, 130));
        Survival_Game.getContentPane().add(LG71, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 120, 130));
        Survival_Game.getContentPane().add(LG72, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 120, 130));
        Survival_Game.getContentPane().add(LG73, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 160, 120, 130));
        Survival_Game.getContentPane().add(LG74, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, 120, 130));
        Survival_Game.getContentPane().add(LG75, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 160, 120, 130));
        Survival_Game.getContentPane().add(LG76, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 160, 120, 130));
        Survival_Game.getContentPane().add(LG87, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 360, 120, 130));
        Survival_Game.getContentPane().add(LG88, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 120, 130));
        Survival_Game.getContentPane().add(LG89, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 120, 130));
        Survival_Game.getContentPane().add(LG90, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, 120, 130));
        Survival_Game.getContentPane().add(LG91, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, 120, 130));
        Survival_Game.getContentPane().add(LG92, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 120, 130));
        Survival_Game.getContentPane().add(LG93, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, 120, 130));
        Survival_Game.getContentPane().add(LG95, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 120, 130));
        Survival_Game.getContentPane().add(LG105, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 360, 120, 130));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1p2_víctorromero/Images/Sun2.png"))); // NOI18N
        Survival_Game.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 110, 100));

        SunBoard2.setBackground(new java.awt.Color(55, 47, 0));
        SunBoard2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        SunBoard2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField3.setBackground(new java.awt.Color(255, 255, 153));
        jTextField3.setFont(new java.awt.Font("Ghostphobia", 1, 45)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setBorder(null);
        SunBoard2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 90, 40));

        jLabel13.setBackground(new java.awt.Color(255, 255, 153));
        jLabel13.setOpaque(true);
        SunBoard2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 10, 110, 40));

        Survival_Game.getContentPane().add(SunBoard2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 170, 60));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1p2_víctorromero/Images/Backyard Dirt.png"))); // NOI18N
        Survival_Game.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 740, 150));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1p2_víctorromero/Images/Backyard Dirt.png"))); // NOI18N
        Survival_Game.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 720, 100));

        PanelSup_Plants2.setBackground(new java.awt.Color(55, 47, 0));
        PanelSup_Plants2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        Panel_Lanzaguisantes5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Panel_Lanzaguisantes5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1p2_víctorromero/Images/Tarjeta_lanzaguisantes.png"))); // NOI18N
        Panel_Lanzaguisantes5.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        Panel_Lanzaguisantes5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Panel_Lanzaguisantes5MouseDragged(evt);
            }
        });
        Panel_Lanzaguisantes5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_Lanzaguisantes5MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Panel_Lanzaguisantes5MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Panel_Lanzaguisantes5MouseReleased(evt);
            }
        });
        PanelSup_Plants2.add(Panel_Lanzaguisantes5);

        Panel_Lanzaguisantes6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Panel_Lanzaguisantes6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1p2_víctorromero/Images/girasol_carta.png"))); // NOI18N
        Panel_Lanzaguisantes6.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        Panel_Lanzaguisantes6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Panel_Lanzaguisantes6MouseDragged(evt);
            }
        });
        Panel_Lanzaguisantes6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_Lanzaguisantes6MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Panel_Lanzaguisantes6MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Panel_Lanzaguisantes6MouseReleased(evt);
            }
        });
        PanelSup_Plants2.add(Panel_Lanzaguisantes6);
        PanelSup_Plants2.add(jPanel1);

        Survival_Game.getContentPane().add(PanelSup_Plants2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 100, 500));

        PanelInf_Plants2.setBackground(new java.awt.Color(86, 86, 2));
        PanelInf_Plants2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Survival_Game.getContentPane().add(PanelInf_Plants2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 120, 520));

        Pause2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1p2_víctorromero/Images/Pause.png"))); // NOI18N
        Pause2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pause2MouseClicked(evt);
            }
        });
        Pause2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pause2ActionPerformed(evt);
            }
        });
        Survival_Game.getContentPane().add(Pause2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 190, 50));

        Adventure_Background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1p2_víctorromero/Images/Background2.jpg"))); // NOI18N
        Survival_Game.getContentPane().add(Adventure_Background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 620));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Survival_Game.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 110, 110));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1p2_víctorromero/Images/ANIMACION3_LanzaGuisantes.gif"))); // NOI18N
        Survival_Game.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        Pause_Screen_TUTORIAL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Pause_Screen_TUTORIAL.setUndecorated(true);
        Pause_Screen_TUTORIAL.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ResumeGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1p2_víctorromero/Images/ResumeGame.png"))); // NOI18N
        ResumeGame.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ResumeGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResumeGameMouseClicked(evt);
            }
        });
        ResumeGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResumeGameActionPerformed(evt);
            }
        });
        Pause_Screen_TUTORIAL.getContentPane().add(ResumeGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 330, 40));

        SaveandLeave.setBackground(new java.awt.Color(24, 24, 55));
        SaveandLeave.setFont(new java.awt.Font("Ghostphobia", 0, 36)); // NOI18N
        SaveandLeave.setForeground(new java.awt.Color(204, 204, 0));
        SaveandLeave.setText("SAVE & LEAVE");
        SaveandLeave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SaveandLeave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveandLeaveMouseClicked(evt);
            }
        });
        Pause_Screen_TUTORIAL.getContentPane().add(SaveandLeave, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 330, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1p2_víctorromero/Images/Pause (SIN Fondo).png"))); // NOI18N
        Pause_Screen_TUTORIAL.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 450));

        Pause_Screen_ADVENTURE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Pause_Screen_ADVENTURE.setUndecorated(true);
        Pause_Screen_ADVENTURE.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ResumeGame1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1p2_víctorromero/Images/ResumeGame.png"))); // NOI18N
        ResumeGame1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ResumeGame1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResumeGame1MouseClicked(evt);
            }
        });
        ResumeGame1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResumeGame1ActionPerformed(evt);
            }
        });
        Pause_Screen_ADVENTURE.getContentPane().add(ResumeGame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 330, 40));

        SaveandLeave1.setBackground(new java.awt.Color(24, 24, 55));
        SaveandLeave1.setFont(new java.awt.Font("Ghostphobia", 0, 36)); // NOI18N
        SaveandLeave1.setForeground(new java.awt.Color(204, 204, 0));
        SaveandLeave1.setText("SAVE & LEAVE");
        SaveandLeave1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SaveandLeave1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveandLeave1MouseClicked(evt);
            }
        });
        Pause_Screen_ADVENTURE.getContentPane().add(SaveandLeave1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 330, 50));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1p2_víctorromero/Images/Pause (SIN Fondo).png"))); // NOI18N
        Pause_Screen_ADVENTURE.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 450));

        Pause_Screen_SURVIVAL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Pause_Screen_SURVIVAL.setUndecorated(true);
        Pause_Screen_SURVIVAL.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ResumeGame2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1p2_víctorromero/Images/ResumeGame.png"))); // NOI18N
        ResumeGame2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ResumeGame2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResumeGame2MouseClicked(evt);
            }
        });
        ResumeGame2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResumeGame2ActionPerformed(evt);
            }
        });
        Pause_Screen_SURVIVAL.getContentPane().add(ResumeGame2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 330, 40));

        SaveandLeave2.setBackground(new java.awt.Color(24, 24, 55));
        SaveandLeave2.setFont(new java.awt.Font("Ghostphobia", 0, 36)); // NOI18N
        SaveandLeave2.setForeground(new java.awt.Color(204, 204, 0));
        SaveandLeave2.setText("SAVE & LEAVE");
        SaveandLeave2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SaveandLeave2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveandLeave2MouseClicked(evt);
            }
        });
        Pause_Screen_SURVIVAL.getContentPane().add(SaveandLeave2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 330, 50));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1p2_víctorromero/Images/Pause (SIN Fondo).png"))); // NOI18N
        Pause_Screen_SURVIVAL.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 450));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Plants vs Zombies (VR Edition)");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cb_users.setBackground(new java.awt.Color(55, 47, 0));
        cb_users.setFont(new java.awt.Font("Ghostphobia", 0, 36)); // NOI18N
        cb_users.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cb_users, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 410, 50));

        NewPlayer.setBackground(new java.awt.Color(0, 102, 0));
        NewPlayer.setFont(new java.awt.Font("Ghostphobia", 0, 24)); // NOI18N
        NewPlayer.setText("New Player!");
        NewPlayer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewPlayerMouseClicked(evt);
            }
        });
        getContentPane().add(NewPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 160, 40));

        VR_Presents.setBackground(new java.awt.Color(0, 0, 0));
        VR_Presents.setFont(new java.awt.Font("Have Heart Two", 0, 70)); // NOI18N
        VR_Presents.setForeground(new java.awt.Color(255, 255, 255));
        VR_Presents.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VR_Presents.setText("Presents");
        getContentPane().add(VR_Presents, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 140, 40));

        VR_PresentsBlack.setFont(new java.awt.Font("Have Heart Two", 0, 70)); // NOI18N
        VR_PresentsBlack.setText("Presents");
        getContentPane().add(VR_PresentsBlack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 140, 40));

        VR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1p2_víctorromero/Images/VRLogo.png"))); // NOI18N
        getContentPane().add(VR, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 160, 90));

        TapToStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1p2_víctorromero/Images/TapToStart2.jpg"))); // NOI18N
        TapToStart.setText("jLabel3");
        TapToStart.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        TapToStart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TapToStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TapToStartMouseClicked(evt);
            }
        });
        getContentPane().add(TapToStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 670, 60));

        Pantalla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Pantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1p2_víctorromero/Images/Main_Screen.jpg"))); // NOI18N
        getContentPane().add(Pantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TapToStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TapToStartMouseClicked
        if (cb_users.getSelectedItem() != null) {
            usuario = (User) cb_users.getSelectedItem();
            lb_name.setText(usuario.getNombre());
            String path = "./src/pro1p2_víctorromero/" + usuario.getNombre() + ".virn";
            administrador = new Administrador(path);
            try {
                administrador.load();
            } catch (IOException ex) {
                Logger.getLogger(Intro.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        this.setVisible(false);
        EA_Presents.setVisible(true);
        EA_Presents.pack();
        EA_Presents.setLocationRelativeTo(this);

        if (audio.isAlive()) {
            audio.getClip().close();
            audio.stop();
        }

        audio = new Audio("./Images/MusicaPVZ.wav");
        audio.start();

    }//GEN-LAST:event_TapToStartMouseClicked

    private void PvZ_LogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PvZ_LogoMouseClicked
        EA_Presents.setVisible(false);
        Main_Screen.setVisible(true);
        Main_Screen.pack();
        Main_Screen.setLocationRelativeTo(this);
    }//GEN-LAST:event_PvZ_LogoMouseClicked

    private void RickRollMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RickRollMouseClicked
        if (Desktop.isDesktopSupported() && Desktop.getDesktop().isSupported(Desktop.Action.BROWSE)) {
            try {
                try {
                    Desktop.getDesktop().browse(new URI("https://www.youtube.com/watch?v=dQw4w9WgXcQ"));
                } catch (URISyntaxException ex) {
                    Logger.getLogger(Intro.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (IOException ex) {
                Logger.getLogger(Intro.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_RickRollMouseClicked

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitMouseClicked

    private void TutorialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TutorialMouseClicked
        Main_Screen.setVisible(false);
        Tutorial_Game.setVisible(true);
        Tutorial_Game.pack();
        Tutorial_Game.setLocationRelativeTo(this);
    }//GEN-LAST:event_TutorialMouseClicked

    private void AdventureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdventureMouseClicked
        Main_Screen.setVisible(false);
        Adventure_Game.setVisible(true);
        Adventure_Game.pack();
        Adventure_Game.setLocationRelativeTo(this);
        gameplay = new Juego(this);

    }//GEN-LAST:event_AdventureMouseClicked

    private void SolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SolMouseClicked
        cantSoles += 25;
        jLabel1.setText(cantSoles + "");

        Sol.setVisible(false);
        VerifPlants();
    }//GEN-LAST:event_SolMouseClicked

    private void PauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PauseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PauseActionPerformed

    private void PauseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PauseMouseClicked
        Pause_Screen_TUTORIAL.setVisible(true);
        Pause_Screen_TUTORIAL.pack();
        Pause_Screen_TUTORIAL.setLocationRelativeTo(this);

//        gm.suspend();
//        t2.suspend();
//        mz.suspend();
    }//GEN-LAST:event_PauseMouseClicked

    private void ResumeGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResumeGameMouseClicked
        Pause_Screen_TUTORIAL.setVisible(false);
        Pause_Screen_TUTORIAL.pack();

//        t.resume();
//        t2.resume();
//        t3.resume();
    }//GEN-LAST:event_ResumeGameMouseClicked

    private void LG1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LG1MouseEntered
        if (poner) {
            lugar = LG1;
        }
    }//GEN-LAST:event_LG1MouseEntered

    private void LG1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LG1MouseReleased
        if (poner) {
            lugar.setIcon(new ImageIcon("./Images\\ANIMACION3_LanzaGuisantes.gif"));
        }
    }//GEN-LAST:event_LG1MouseReleased

    private void NewPlayerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewPlayerMouseClicked
        String nombre = JOptionPane.showInputDialog("Ingrese nombre de usuario");
        int validar = 0;
        for (User u : userAdministrador.getUsersList()) {
            if (nombre.equals(u.getNombre())) {
                validar++;
                break;
            }
        }

        if (validar == 0) {
            User nuevo = new User(nombre);
            userAdministrador.getUsersList().add(nuevo);
            userAdministrador.add();
            LlenarUsuarios();
        } else {
            JOptionPane.showMessageDialog(this, "Nombre Repetido");
        }

    }//GEN-LAST:event_NewPlayerMouseClicked

    private void Panel_Lanzaguisantes5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_Lanzaguisantes5MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_Panel_Lanzaguisantes5MouseDragged

    private void Panel_Lanzaguisantes5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_Lanzaguisantes5MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Panel_Lanzaguisantes5MousePressed

    private void Panel_Lanzaguisantes5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_Lanzaguisantes5MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_Panel_Lanzaguisantes5MouseReleased

    private void Panel_Lanzaguisantes6MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_Lanzaguisantes6MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_Panel_Lanzaguisantes6MouseDragged

    private void Panel_Lanzaguisantes6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_Lanzaguisantes6MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Panel_Lanzaguisantes6MousePressed

    private void Panel_Lanzaguisantes6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_Lanzaguisantes6MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_Panel_Lanzaguisantes6MouseReleased

    private void SaveandLeaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveandLeaveMouseClicked
        Pause_Screen_TUTORIAL.setVisible(false);
        Pause_Screen_TUTORIAL.pack();
        Tutorial_Game.setVisible(false);

        //Falta STOP THREADS
        Main_Screen.setVisible(true);
        Main_Screen.setLocationRelativeTo(this);
        Main_Screen.pack();
    }//GEN-LAST:event_SaveandLeaveMouseClicked

    private void ResumeGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResumeGameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResumeGameActionPerformed

    private void ResumeGame1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResumeGame1MouseClicked
        Pause_Screen_ADVENTURE.setVisible(false);
        Pause_Screen_ADVENTURE.pack();

    }//GEN-LAST:event_ResumeGame1MouseClicked

    private void ResumeGame1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResumeGame1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResumeGame1ActionPerformed

    private void SaveandLeave1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveandLeave1MouseClicked
        Pause_Screen_ADVENTURE.setVisible(false);
        Pause_Screen_ADVENTURE.pack();
        Adventure_Game.setVisible(false);

        //Falta STOP THREADS
        Main_Screen.setVisible(true);
        Main_Screen.setLocationRelativeTo(this);
        Main_Screen.pack();
    }//GEN-LAST:event_SaveandLeave1MouseClicked

    private void ResumeGame2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResumeGame2MouseClicked
        Pause_Screen_SURVIVAL.setVisible(false);
        Pause_Screen_SURVIVAL.pack();

    }//GEN-LAST:event_ResumeGame2MouseClicked

    private void ResumeGame2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResumeGame2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResumeGame2ActionPerformed

    private void SaveandLeave2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveandLeave2MouseClicked
        Pause_Screen_SURVIVAL.setVisible(false);
        Pause_Screen_SURVIVAL.pack();
        Survival_Game.setVisible(false);

        //Falta STOP THREADS
        Main_Screen.setVisible(true);
        Main_Screen.setLocationRelativeTo(this);
        Main_Screen.pack();
    }//GEN-LAST:event_SaveandLeave2MouseClicked

    private void Pause1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pause1MouseClicked
        Pause_Screen_ADVENTURE.setVisible(true);
        Pause_Screen_ADVENTURE.pack();
        Pause_Screen_ADVENTURE.setLocationRelativeTo(this);
    }//GEN-LAST:event_Pause1MouseClicked

    private void Pause1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pause1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pause1ActionPerformed

    private void Pause2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pause2MouseClicked
        Pause_Screen_SURVIVAL.setVisible(true);
        Pause_Screen_SURVIVAL.pack();
        Pause_Screen_SURVIVAL.setLocationRelativeTo(this);
    }//GEN-LAST:event_Pause2MouseClicked

    private void Pause2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pause2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pause2ActionPerformed

    private void SurvivalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SurvivalMouseClicked
        Main_Screen.setVisible(false);
        Survival_Game.setVisible(true);
        Survival_Game.pack();
        Survival_Game.setLocationRelativeTo(this);
    }//GEN-LAST:event_SurvivalMouseClicked

    private void Sol1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sol1MouseClicked
        gameplay.clickSol();
    }//GEN-LAST:event_Sol1MouseClicked

    private void Panel_Lanzaguisantes3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_Lanzaguisantes3MouseClicked
        Panel_Lanzaguisantes3.setBorder(BorderFactory.createEtchedBorder(Color.WHITE, Color.blue));
        gameplay.plantar = Juego.TipoPlanta.GUISANTE;
    }//GEN-LAST:event_Panel_Lanzaguisantes3MouseClicked

    private void Panel_Lanzaguisantes2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_Lanzaguisantes2MouseClicked
        Panel_Lanzaguisantes2.setBorder(BorderFactory.createEtchedBorder(Color.WHITE, Color.blue));
        gameplay.plantar = Juego.TipoPlanta.GIRASOL;
    }//GEN-LAST:event_Panel_Lanzaguisantes2MouseClicked

    private void Panel_Lanzaguisantes4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_Lanzaguisantes4MouseClicked
        Panel_Lanzaguisantes4.setBorder(BorderFactory.createEtchedBorder(Color.WHITE, Color.blue));
        gameplay.plantar=Juego.TipoPlanta.CHERRYBOMB;    }//GEN-LAST:event_Panel_Lanzaguisantes4MouseClicked

    private void Panel_Lanzaguisantes5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_Lanzaguisantes5MouseClicked
        Panel_Lanzaguisantes5.setBorder(BorderFactory.createEtchedBorder(Color.WHITE, Color.blue));
        gameplay.plantar = Juego.TipoPlanta.GUISANTE;
    }//GEN-LAST:event_Panel_Lanzaguisantes5MouseClicked

    private void Panel_Lanzaguisantes6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_Lanzaguisantes6MouseClicked
        Panel_Lanzaguisantes6.setBorder(BorderFactory.createEtchedBorder(Color.WHITE, Color.blue));
        gameplay.plantar = Juego.TipoPlanta.GIRASOL;
    }//GEN-LAST:event_Panel_Lanzaguisantes6MouseClicked

    private void Panel_LanzaguisantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_LanzaguisantesMouseClicked
        Panel_Lanzaguisantes.setBorder(BorderFactory.createEtchedBorder(Color.WHITE, Color.blue));
        gameplay.plantar = Juego.TipoPlanta.GUISANTE;
    }//GEN-LAST:event_Panel_LanzaguisantesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Intro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Intro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Intro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Intro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Intro().setVisible(true);
            }
        }
        );
    }

    public void LlenarUsuarios() {
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_users.getModel();
        modelo.removeAllElements();
        for (User u : userAdministrador.getUsersList()) {
            modelo.addElement(u);
        }
    }

    public void VerifPlants() {
        if (cantSoles >= 100) {
            Panel_Lanzaguisantes.setEnabled(true);

            jLabel1.setText(cantSoles + "");
        }

    }

    public void Disparo(DisparoLanzaguisantes gm, MoveZombies mz) {
        if (gm.getX() == mz.getX()) {
            zombies.setHealth(zombies.getHealth() - 25);
        }
        if (zombies.getHealth() <= 0) {
            mz.getLabel().setVisible(false);
        }
        System.out.println(gm.getX() + "---->" + gm.getY());
    }

    //Coords
    private int xMouse;
    private int yMouse;
    private int cantSoles = 100;

    //Thread Cracion de Soles
    GeneradorSol gs;
    Thread t2 = new Thread(gs);

    //MoveZombies
    private boolean poner = false;
    private JLabel lugar = new JLabel();
    private Zombies zombies;
    private boolean vidaZombies = true;

    //Songs
    private Audio audio = new Audio();

    //Archivos Binarios
    private AdministradorUsuario userAdministrador;
    private Administrador administrador;
    private User usuario;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Adventure;
    private javax.swing.JLabel Adventure_Background1;
    private javax.swing.JLabel Adventure_Background2;
    public javax.swing.JFrame Adventure_Game;
    private javax.swing.JFrame EA_Presents;
    private javax.swing.JLabel EA_VR;
    private javax.swing.JLabel EA_VRBlack;
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel GamePlay;
    private javax.swing.JLabel Girasol;
    public javax.swing.JLabel LG1;
    public javax.swing.JLabel LG10;
    public javax.swing.JLabel LG105;
    public javax.swing.JLabel LG11;
    public javax.swing.JLabel LG12;
    public javax.swing.JLabel LG13;
    public javax.swing.JLabel LG14;
    public javax.swing.JLabel LG15;
    public javax.swing.JLabel LG16;
    public javax.swing.JLabel LG17;
    public javax.swing.JLabel LG18;
    public javax.swing.JLabel LG19;
    public javax.swing.JLabel LG2;
    public javax.swing.JLabel LG20;
    public javax.swing.JLabel LG21;
    public javax.swing.JLabel LG22;
    public javax.swing.JLabel LG23;
    public javax.swing.JLabel LG24;
    public javax.swing.JLabel LG25;
    public javax.swing.JLabel LG26;
    public javax.swing.JLabel LG27;
    public javax.swing.JLabel LG28;
    public javax.swing.JLabel LG29;
    public javax.swing.JLabel LG3;
    public javax.swing.JLabel LG30;
    public javax.swing.JLabel LG31;
    public javax.swing.JLabel LG32;
    public javax.swing.JLabel LG33;
    public javax.swing.JLabel LG34;
    public javax.swing.JLabel LG35;
    public javax.swing.JLabel LG36;
    public javax.swing.JLabel LG37;
    public javax.swing.JLabel LG38;
    public javax.swing.JLabel LG39;
    public javax.swing.JLabel LG4;
    public javax.swing.JLabel LG40;
    public javax.swing.JLabel LG41;
    public javax.swing.JLabel LG42;
    public javax.swing.JLabel LG43;
    public javax.swing.JLabel LG44;
    public javax.swing.JLabel LG45;
    public javax.swing.JLabel LG46;
    public javax.swing.JLabel LG47;
    public javax.swing.JLabel LG48;
    public javax.swing.JLabel LG49;
    public javax.swing.JLabel LG5;
    public javax.swing.JLabel LG50;
    public javax.swing.JLabel LG51;
    public javax.swing.JLabel LG52;
    public javax.swing.JLabel LG53;
    public javax.swing.JLabel LG54;
    public javax.swing.JLabel LG55;
    public javax.swing.JLabel LG56;
    public javax.swing.JLabel LG57;
    public javax.swing.JLabel LG58;
    public javax.swing.JLabel LG59;
    public javax.swing.JLabel LG6;
    public javax.swing.JLabel LG60;
    public javax.swing.JLabel LG61;
    public javax.swing.JLabel LG62;
    public javax.swing.JLabel LG63;
    public javax.swing.JLabel LG64;
    public javax.swing.JLabel LG65;
    public javax.swing.JLabel LG66;
    public javax.swing.JLabel LG67;
    public javax.swing.JLabel LG68;
    public javax.swing.JLabel LG69;
    public javax.swing.JLabel LG7;
    public javax.swing.JLabel LG70;
    public javax.swing.JLabel LG71;
    public javax.swing.JLabel LG72;
    public javax.swing.JLabel LG73;
    public javax.swing.JLabel LG74;
    public javax.swing.JLabel LG75;
    public javax.swing.JLabel LG76;
    public javax.swing.JLabel LG8;
    public javax.swing.JLabel LG87;
    public javax.swing.JLabel LG88;
    public javax.swing.JLabel LG89;
    public javax.swing.JLabel LG9;
    public javax.swing.JLabel LG90;
    public javax.swing.JLabel LG91;
    public javax.swing.JLabel LG92;
    public javax.swing.JLabel LG93;
    public javax.swing.JLabel LG95;
    private javax.swing.JLabel Lanzaguisantes;
    private javax.swing.JLabel MainScreen;
    private javax.swing.JFrame Main_Screen;
    private javax.swing.JButton NewPlayer;
    private javax.swing.JPanel PanelInf_Plants;
    private javax.swing.JPanel PanelInf_Plants1;
    private javax.swing.JPanel PanelInf_Plants2;
    private javax.swing.JPanel PanelSup_Plants;
    private javax.swing.JPanel PanelSup_Plants1;
    private javax.swing.JPanel PanelSup_Plants2;
    public javax.swing.JLabel Panel_Lanzaguisantes;
    public javax.swing.JLabel Panel_Lanzaguisantes2;
    public javax.swing.JLabel Panel_Lanzaguisantes3;
    public javax.swing.JLabel Panel_Lanzaguisantes4;
    private javax.swing.JLabel Panel_Lanzaguisantes5;
    private javax.swing.JLabel Panel_Lanzaguisantes6;
    private javax.swing.JLabel Pantalla;
    private javax.swing.JButton Pause;
    private javax.swing.JButton Pause1;
    private javax.swing.JButton Pause2;
    private javax.swing.JFrame Pause_Screen_ADVENTURE;
    private javax.swing.JFrame Pause_Screen_SURVIVAL;
    private javax.swing.JFrame Pause_Screen_TUTORIAL;
    private javax.swing.JLabel Presents;
    private javax.swing.JLabel PresentsBlack;
    private javax.swing.JLabel Press;
    private javax.swing.JLabel PressBlack;
    private javax.swing.JLabel PvZ_Logo;
    private javax.swing.JButton ResumeGame;
    private javax.swing.JButton ResumeGame1;
    private javax.swing.JButton ResumeGame2;
    private javax.swing.JLabel RickRoll;
    private javax.swing.JButton SaveandLeave;
    private javax.swing.JButton SaveandLeave1;
    private javax.swing.JButton SaveandLeave2;
    public javax.swing.JLabel Sol;
    public javax.swing.JLabel Sol1;
    private javax.swing.JPanel SunBoard;
    private javax.swing.JPanel SunBoard1;
    private javax.swing.JPanel SunBoard2;
    private javax.swing.JLabel Survival;
    private javax.swing.JFrame Survival_Game;
    private javax.swing.JLabel TapToStart;
    private javax.swing.JLabel Tutorial;
    private javax.swing.JLabel Tutorial1;
    private javax.swing.JLabel Tutorial_Background;
    private javax.swing.JFrame Tutorial_Game;
    private javax.swing.JLabel VR;
    private javax.swing.JLabel VR_Presents;
    private javax.swing.JLabel VR_PresentsBlack;
    private javax.swing.JComboBox<String> cb_users;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lb_name;
    // End of variables declaration//GEN-END:variables

}
